<?php

$title = 'My agencies';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('agency', array('action'=>'add'));?>">Add new agency</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($agencies as $agency) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($agency->title);?></td>
            <td><?php echo $this->escapeHtml($agency->description);?></td>
            <td>
                <a href="<?php echo $this->url('agency',
                    array('action'=>'edit', 'id' => $agency->id));?>">Edit</a>
                <a href="<?php echo $this->url('agency',
                    array('action'=>'delete', 'id' => $agency->id));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>