<?php
$title = 'Добавить группу объявлений';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url(
    'group',
    array(
        'action' => 'add',
        'id'     => $this->id,
    )
));
$form->prepare();
?>
<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
        <br>
        <div class="panel panel-default">
            <div class="panel-body">

                <?php echo $this->form()->openTag($form);?>
                <?php echo $this->formElement($form->get('id'));?>
                <div class="input-group">
                    <?php echo $this->formElement($form->get('name'));?>
                    <span class="input-group-addon" id="basic-addon2">Название</span>
                </div>
                <br>
                <div class="input-group">
                    <?php echo $this->formElement($form->get('submit'));?>
                </div>

                <?php echo $this->form()->closeTag();?>

            </div>
        </div>
    </div>
</div>



