<?php

$title = 'Удалить группу объявлений';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Вы действительно хотите удалить
    '<?php echo $this->escapeHtml($group->name); ?>'?
</p>
<?php
$url = $this->url('group', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $group->id; ?>" />
        <input type="submit" name="del" value="Да" />
        <input type="submit" name="del" value="Нет" />
    </div>
</form>