<?php

$title = 'Список групп объявлений';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('group', array('action'=>'add'));?>">Добавить новую группу</a>
</p>

<table class="table">
    <tr>
        <th>Название</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($groups as $item) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($item->name);?></td>
            <td>
                <a href="<?php echo $this->url('group',
                    array('action'=>'edit', 'id' => $item->id));?>">Редактировать</a>
                <a href="<?php echo $this->url('group',
                    array('action'=>'delete', 'id' => $item->id));?>">Удалить</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>